import type { IncomingMessage, ServerResponse } from 'node:http';
import type { Axiomify } from '@axiomify/core';
import fs from 'node:fs';
import path from 'node:path';
import { sendJson, readBody } from '../server/http-server';
import {
  redactForStudio,
  sanitizeRecordedBody,
  sanitizeRecordedHeaders,
} from './privacy';

type RequestFields = Record<string, string | string[] | undefined>;

export interface ReplayItem {
  id: string;
  method: string;
  path: string;
  headers: RequestFields;
  query: RequestFields;
  body: unknown;
  timestamp: string;
}

const HISTORY_FILE = path.join(process.cwd(), '.axiomify-studio-history.json');
const instrumentedApps = new WeakSet<object>();
let debounceTimer: NodeJS.Timeout | null = null;

/** Apply Studio's recording policy before a replay can reach memory or disk. */
export function sanitizeReplayItem(item: ReplayItem): ReplayItem {
  return {
    ...item,
    headers: sanitizeRecordedHeaders(item.headers || {}),
    query: redactForStudio(item.query || {}) as RequestFields,
    body: sanitizeRecordedBody(item.body),
  };
}

function loadHistory(): ReplayItem[] {
  try {
    if (fs.existsSync(HISTORY_FILE)) {
      const data = fs.readFileSync(HISTORY_FILE, 'utf8');
      const parsed = JSON.parse(data);
      if (!Array.isArray(parsed)) return [];
      const sanitized = parsed
        .filter((item): item is ReplayItem => item && typeof item === 'object')
        .map((item) => sanitizeReplayItem(item));

      // Upgrade old Studio history in place: raw secrets from a previous
      // Studio version must not remain on disk after Studio starts.
      if (JSON.stringify(parsed) !== JSON.stringify(sanitized)) {
        try {
          fs.writeFileSync(
            HISTORY_FILE,
            JSON.stringify(sanitized, null, 2),
            'utf8',
          );
        } catch (err) {
          // Continue with the protected in-memory copy even if a read-only
          // working directory prevents migration of the old file.
          console.warn(
            '[Studio] Failed to redact existing replay history:',
            err,
          );
        }
      }
      return sanitized;
    }
  } catch (err) {
    // Silently default to empty list on parsing/loading errors
  }
  return [];
}

export function saveHistory(): void {
  if (debounceTimer) {
    clearTimeout(debounceTimer);
  }

  debounceTimer = setTimeout(() => {
    debounceTimer = null;
    fs.promises
      .writeFile(HISTORY_FILE, JSON.stringify(requestHistory, null, 2), 'utf8')
      .catch((err) => {
        console.warn('[Studio] Failed to save request history:', err);
      });
  }, 200);
  debounceTimer.unref?.();
}

export const requestHistory: ReplayItem[] = loadHistory();

export async function handlePostRequestReplay(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<void> {
  try {
    const rawBody = await readBody(req);
    const payload = JSON.parse(rawBody);

    if (payload.id && payload.method && payload.path) {
      requestHistory.push(
        sanitizeReplayItem({
          id: payload.id,
          method: payload.method,
          path: payload.path,
          headers: payload.headers || {},
          query: payload.query || {},
          body: payload.body,
          timestamp: new Date().toISOString(),
        }),
      );
      if (requestHistory.length > 50) {
        requestHistory.shift();
      }
      saveHistory();
      sendJson(res, { success: true });
    } else {
      sendJson(res, { error: 'Invalid replay payload' }, 400);
    }
  } catch (err: any) {
    sendJson(res, { error: err.message }, 500);
  }
}

let onReplayUpdatedCallback: (() => void) | null = null;

export function setOnReplayUpdated(cb: () => void): void {
  onReplayUpdatedCallback = cb;
}

export function notifyReplaysUpdated(): void {
  if (onReplayUpdatedCallback) {
    onReplayUpdatedCallback();
  }
}

export function instrumentRequestReplay(app: Axiomify): void {
  if (instrumentedApps.has(app)) return;
  instrumentedApps.add(app);

  try {
    app.addHook('onRequest', (req: any) => {
      if (!req) return;

      const reqPath =
        req.path ||
        (req.url ? new URL(req.url, 'http://localhost').pathname : '/');

      // Avoid tracking studio's internal API requests
      if (reqPath.startsWith('/__studio/')) return;

      // Avoid tracking requests generated by the proxy to prevent double adding
      if (req.id && req.id.startsWith('studio-')) return;

      const item: ReplayItem = sanitizeReplayItem({
        id: `replay-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
        method: (req.method || 'GET').toUpperCase(),
        path: reqPath,
        headers: req.headers || {},
        query: req.query || {},
        body: req.body,
        timestamp: new Date().toISOString(),
      });

      requestHistory.push(item);
      if (requestHistory.length > 50) {
        requestHistory.shift();
      }
      saveHistory();
      notifyReplaysUpdated();
    });
  } catch (err) {
    console.warn('[Studio] Failed to instrument request replay hook:', err);
  }
}

export function handleGetRequestReplays(_req: any, res: ServerResponse): void {
  sendJson(res, { history: requestHistory });
}

export function handleDeleteRequestReplay(
  req: IncomingMessage,
  res: ServerResponse,
): void {
  try {
    const url = new URL(
      req.url || '',
      `http://${req.headers.host || 'localhost'}`,
    );
    const id = url.searchParams.get('id');
    if (!id) {
      sendJson(res, { error: 'Missing "id" parameter' }, 400);
      return;
    }
    const index = requestHistory.findIndex((item) => item.id === id);
    if (index !== -1) {
      requestHistory.splice(index, 1);
      saveHistory();
      notifyReplaysUpdated();
      sendJson(res, { success: true });
    } else {
      sendJson(res, { error: 'Item not found' }, 404);
    }
  } catch (err: any) {
    sendJson(res, { error: err.message }, 500);
  }
}

export function handleDeleteAllRequestReplays(
  _req: IncomingMessage,
  res: ServerResponse,
): void {
  try {
    requestHistory.length = 0;
    saveHistory();
    notifyReplaysUpdated();
    sendJson(res, { success: true });
  } catch (err: any) {
    sendJson(res, { error: err.message }, 500);
  }
}
