import { Project, TypeFormatFlags } from "ts-morph";
import fs from "fs";
import path from "path";
import { registry } from "../core/registry";

/**
 * Generates a zero-dependency typed client for the frontend.
 * Outputs two files:
 * 1. axiomify-env.d.ts (Pure TypeScript types)
 * 2. axiomify-client.js (Tiny runtime map for the proxy)
 */
export async function runGenerateCommand() {
  console.log("🔍 Analyzing AST for client generation...");

  const cwd = process.cwd();
  const routes = registry.getAllRoutes();

  // 1. Initialize the TypeScript Compiler API context
  const project = new Project({
    tsConfigFilePath: path.join(cwd, "tsconfig.json"),
    skipAddingFilesFromTsConfig: true,
  });

  const routeFiles = routes.map((r) => r.filePath);
  project.addSourceFilesAtPaths(routeFiles);

  let typeDefinition = `// AUTO-GENERATED BY AXIOMIFY\n\nexport type AppRouter = {\n`;
  const runtimeMap: Record<string, { method: string; path: string }> = {};

  for (const route of routes) {
    const sourceFile = project.getSourceFileOrThrow(route.filePath);

    // 2. Locate the `export default route(...)` node
    const defaultExport = sourceFile.getExportAssignment(
      (d) => !d.isExportEquals(),
    );
    if (!defaultExport) continue;

    // 3. Ask the TS compiler for the exact, fully resolved return type of the route function
    const routeType = defaultExport.getExpression().getType();

    // 4. Convert the compiler type back to a clean string
    const typeText = routeType.getText(
      undefined,
      TypeFormatFlags.NoTruncation | TypeFormatFlags.InTypeAlias,
    );

    // 5. Build the nested key path (e.g., 'users.getUser')
    const routeKey = getRouteKey(cwd, route.filePath);
    typeDefinition += `  "${routeKey}": ${typeText};\n`;

    // 6. Populate the runtime map
    runtimeMap[routeKey] = {
      method: route.config.method,
      path: route.config.path,
    };
  }

  typeDefinition += `};\n`;

  // 7. Write the artifacts to the file system
  fs.writeFileSync(path.join(cwd, "axiomify-env.d.ts"), typeDefinition);
  fs.writeFileSync(
    path.join(cwd, "axiomify-client.js"),
    `export const routeMap = ${JSON.stringify(runtimeMap, null, 2)};`,
  );

  console.log("✅ Generated typed client artifacts successfully.");
}

/**
 * Helper: Converts file paths to dot-notation keys.
 * src/routes/users/get.ts -> 'users.get'
 */
function getRouteKey(cwd: string, filePath: string): string {
  const relative = path.relative(path.join(cwd, "src", "routes"), filePath);
  return relative.replace(/\.ts$/, "").split(path.sep).join(".");
}
