import fs from 'fs';
import { createJiti } from 'jiti';
import path from 'path';
import { Project, TypeFormatFlags } from 'ts-morph';
import { registry } from '../core/registry';
import { scanAndRegisterRoutes } from '../scanner';

export async function runGenerateCommand() {
  console.log('🔍 Analyzing AST for client generation...');

  const cwd = process.cwd();
  const configPath = path.join(cwd, 'axiomify.config.ts');
  let routesDir = 'src/routes';
  let outDir = 'src';

  if (fs.existsSync(configPath)) {
    const jiti = createJiti(path.join(cwd, 'index.js'));
    const importedConfig = await jiti.import(configPath, { default: true });
    const rawConfig: any = importedConfig || {};
    const config = rawConfig.default || rawConfig;
    if (config.routesDir) routesDir = config.routesDir;
    if (config.outputDir) outDir = config.outputDir;
  }

  await scanAndRegisterRoutes({ routesDir: path.join(cwd, routesDir) });

  const routes = registry.getAllRoutes();
  if (routes.length === 0) {
    console.log('⚠️  No routes found. Cannot generate client.');
    return;
  }

  const project = new Project({
    tsConfigFilePath: path.join(cwd, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });

  const routeFiles = routes.map((r) => r.filePath);
  project.addSourceFilesAtPaths(routeFiles);

  // Notice: No external imports needed anymore!
  let typeDefinition = `/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED BY AXIOMIFY - DO NOT EDIT MANUALLY

`;

  const runtimeMap: Record<string, { method: string; path: string }> = {};
  const typeFormat = TypeFormatFlags.NoTruncation;
  const nestedObj: any = {};

  for (const route of routes) {
    const sourceFile = project.getSourceFileOrThrow(route.filePath);
    const defaultExport = sourceFile.getExportAssignment(
      (d) => !d.isExportEquals(),
    );
    if (!defaultExport) continue;

    const callExpr = defaultExport.getExpression();
    if (callExpr.getKindName() !== 'CallExpression') continue;

    const routeType = callExpr.getType();
    const typeArgs = routeType.getTypeArguments();

    const sanitize = (t: string) => t.replace(/import\(".*?"\)\./g, '').trim();

    const pType = typeArgs[0]
      ? sanitize(typeArgs[0].getText(undefined, typeFormat))
      : 'void';
    const qType = typeArgs[1]
      ? sanitize(typeArgs[1].getText(undefined, typeFormat))
      : 'void';
    const bType = typeArgs[2]
      ? sanitize(typeArgs[2].getText(undefined, typeFormat))
      : 'void';
    const rType = typeArgs[3]
      ? sanitize(typeArgs[3].getText(undefined, typeFormat))
      : 'void';

    const isVoid = (t: string) =>
      t === 'void' || t === 'undefined' || t === 'never' || t === 'unknown';

    // ✨ Build the inline payload object dynamically
    const payloadProps = [];
    if (!isVoid(pType)) payloadProps.push(`params: ${pType}`);
    if (!isVoid(qType)) payloadProps.push(`query: ${qType}`);
    if (!isVoid(bType)) payloadProps.push(`body: ${bType}`);

    payloadProps.push(`headers?: Record<string, string>`);

    const hasRequired = !isVoid(pType) || !isVoid(qType) || !isVoid(bType);
    const payloadStr = `{ ${payloadProps.join('; ')} }`;

    // Strict typing: if no body/params/query, payload is entirely optional
    const methodStr = hasRequired
      ? `(payload: ${payloadStr}) => Promise<${rType}>`
      : `(payload?: ${payloadStr}) => Promise<${rType}>`;

    const relativeDir = path.relative(
      path.join(cwd, routesDir),
      route.filePath,
    );
    const parts = relativeDir.replace(/\.ts$/, '').split(path.sep);
    const routeKey = parts.join('.');

    runtimeMap[routeKey] = {
      method: route.config.method as string,
      path: route.config.path as string,
    };

    let current = nestedObj;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!current[parts[i]]) current[parts[i]] = {};
      current = current[parts[i]];
    }
    current[parts[parts.length - 1]] = methodStr;
  }

  function stringifyInterface(obj: any, indent = '  '): string {
    let str = '{\n';
    for (const [key, value] of Object.entries(obj)) {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
      if (typeof value === 'string') {
        str += `${indent}${safeKey}: ${value};\n`;
      } else {
        str += `${indent}${safeKey}: ${stringifyInterface(value, indent + '  ')}\n`;
      }
    }
    str += indent.substring(2) + '}';
    return str;
  }

  typeDefinition += `export interface AppRouter ${stringifyInterface(nestedObj)}\n\n`;
  typeDefinition += `export const routeMap: Record<string, { method: string; path: string }> = ${JSON.stringify(runtimeMap, null, 2)};\n`;

  const absoluteOutDir = path.join(cwd, outDir);
  if (!fs.existsSync(absoluteOutDir)) {
    fs.mkdirSync(absoluteOutDir, { recursive: true });
  }

  const outPath = path.join(absoluteOutDir, 'axiomify.ts');
  fs.writeFileSync(outPath, typeDefinition);

  console.log(
    `✨ Generated self-contained client artifact at ${outDir}/axiomify.ts`,
  );
}
