import { Project, TypeFormatFlags } from 'ts-morph';
import fs from 'fs';
import path from 'path';
import { registry } from '../core/registry';

export async function runGenerateCommand() {
  console.log('🔍 Analyzing AST for client generation...');

  const cwd = process.cwd();
  const routes = registry.getAllRoutes();
  const project = new Project({
    tsConfigFilePath: path.join(cwd, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });

  const routeFiles = routes.map((r) => r.filePath);
  project.addSourceFilesAtPaths(routeFiles);

  // 1. Define the base utility types for the generated file
  let typeDefinition = `// AUTO-GENERATED BY AXIOMIFY
export interface ClientRouteMeta<P, Q, B, R> {
  params: P;
  query: Q;
  body: B;
  response: R;
}

export interface AppRouter {\n`;

  const runtimeMap: Record<string, { method: string; path: string }> = {};
  const typeFormat = TypeFormatFlags.NoTruncation | TypeFormatFlags.InTypeAlias;

  for (const route of routes) {
    const sourceFile = project.getSourceFileOrThrow(route.filePath);
    const defaultExport = sourceFile.getExportAssignment(
      (d) => !d.isExportEquals(),
    );
    if (!defaultExport) continue;

    // 2. Extract the argument passed to route()
    const callExpr = defaultExport.getExpression();
    if (callExpr.getKindName() !== 'CallExpression') continue;

    // 3. Extract the exact generic types resolved by the TypeScript compiler
    const routeType = callExpr.getType();
    const typeArgs = routeType.getTypeArguments();

    // Map the generic parameters from RouteDefinition<P, Q, B, R, Plugins>
    const pType = typeArgs[0]
      ? typeArgs[0].getText(undefined, typeFormat)
      : 'void';
    const qType = typeArgs[1]
      ? typeArgs[1].getText(undefined, typeFormat)
      : 'void';
    const bType = typeArgs[2]
      ? typeArgs[2].getText(undefined, typeFormat)
      : 'void';
    const rType = typeArgs[3]
      ? typeArgs[3].getText(undefined, typeFormat)
      : 'void';

    const routeKey = getRouteKey(cwd, route.filePath);
    typeDefinition += `  "${routeKey}": ClientRouteMeta<${pType}, ${qType}, ${bType}, ${rType}>;\n`;

    runtimeMap[routeKey] = {
      method: route.config.method,
      path: route.config.path,
    };
  }

  typeDefinition += `};\n`;

  fs.writeFileSync(path.join(cwd, 'axiomify-env.d.ts'), typeDefinition);
  fs.writeFileSync(
    path.join(cwd, 'axiomify-client.js'),
    `export const routeMap = ${JSON.stringify(runtimeMap, null, 2)};`,
  );

  console.log('✅ Generated strict typed client artifacts successfully.');
}

function getRouteKey(cwd: string, filePath: string): string {
  const relative = path.relative(path.join(cwd, 'src', 'routes'), filePath);
  return relative.replace(/\.ts$/, '').split(path.sep).join('.');
}
