/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED BY AXIOMIFY - DO NOT EDIT MANUALLY

export interface AppRouter {
  health: (payload?: { headers?: Record<string, string> }) => Promise<{ status: string; engine: string; uptime: number; }>;
  ping: (payload?: { headers?: Record<string, string> }) => Promise<{ message: string; timestamp: number; }>;
  users: {
    create: (payload: { body: { email: string; name: string; }; headers?: Record<string, string> }) => Promise<{ success: boolean; userId: string; createdBy: string; }>;
  }
  posts: {
    _id: (payload?: { headers?: Record<string, string> }) => Promise<{ message: string; success: boolean; }>;
  }
}

export const routeMap: Record<string, { method: string; path: string }> = {
  "health": {
    "method": "GET",
    "path": "/health"
  },
  "ping": {
    "method": "GET",
    "path": "/v1/ping"
  },
  "users.create": {
    "method": "POST",
    "path": "/users"
  },
  "posts._id": {
    "method": "GET",
    "path": "/posts/:id"
  }
};
